<template>
    <div class="logo-container">
        <div class="logo">
            <img class="face" src="../assets/Logo no eyes.svg" alt="">
            <img class="left-eye rotate-center" src="../assets/lefteye.svg" alt="">
            <img class="right-eye rotate-alt" src="../assets/righteye.svg" alt="">
        </div>
        <div class="tag-line">
            <img src="../assets/logo text.png" alt="">
        </div>
    </div>
</template>

<script>
    export default {
        name: "SplashScreen"
    }
</script>

<style scoped>
    .logo-container {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        background: white;
        height: 100vh;
    }

    .logo {
        position: relative;
    }

    .left-eye{
        position: absolute;
        top: 58px;
        left: 61px;
    }

    .right-eye {
        position: absolute;
        top: 57px;
        right: 64px;
    }

    .rotate-center {
        animation: rotate-center 0.8s ease-in-out infinite alternate both;
    }

    .rotate-alt {
        animation: rotate-center 0.8s linear infinite alternate forwards;
    }

    .tag-line {
        margin-top: 50px;
    }

    /* ----------------------------------------------
 * Generated by Animista on 2019-9-21 13:31:23
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

    /**
     * ----------------------------------------
     * animation rotate-center
     * ----------------------------------------
     */
    @keyframes rotate-center {
        0% {
            transform: rotate(0);
        }
        100% {
            transform: rotate(360deg);
        }
    }

</style>